dist: trusty
language: java
jdk:
  - openjdk11
  - oraclejdk8
env:
  global:
  - BUILD_SYSTEM=travis
  matrix:
  - DB=h2
  - DB=postgresql
  - DB=mysql
  - DB=mariadb
  - DB=sqlserver
  - DB=db2
addons:
  postgresql: "9.6"
services:
  - docker
before_install:
  - mkdir -p $HOME/.m2
  - cp travis/maven_settings.xml $HOME/.m2/settings.xml
before_script:
  - export SPRING_PROFILES_ACTIVE=nflow.db.$DB
  - ./travis/setup-db-$DB.sh
script:
  - mvn jacoco:prepare-agent test -B -P $DB
after_script:
  - for i in nflow-*/target/surefire-reports/*.txt; do echo ">>>>>>>>>>>>>>>>>>>"; echo $i; echo "<<<<<<<<<<<<<<<<<<<<<"; cat $i; done
notifications:
  flowdock:
    secure: QbIGfsj64a2Ms5y/aTO0PUAVBRv9mKxAwLFj5NxWACEVxm1JKZvrQ4ov/8XbVRbRl96sMIoWPox7Gu++ZgLjb7w+jeiCvWLwJwRDxlCgsYvb4hAcPXlNBO7SF4kcUifPfJpaDsb3EThUUK8EtsI5aOxvCqGKMChTDoQnej3kc0o=
after_success:
  - mvn jacoco:report coveralls:report
cache:
  directories:
  - $HOME/.m2/repository
sudo: false

