language: node_js
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - gem install sass
  - gem install compass

node_js:
  - '0.10'

before_script:
  - 'npm install -g bower grunt-cli'
  - 'npm install'
  - 'bower install'
  - 'node_modules/protractor/bin/webdriver-manager update'
  - 'node_modules/protractor/bin/webdriver-manager start'

script: grunt itest

